[language-server.astro-ls-local]
command = "bun"
args = ["--bun", "./node_modules/.bin/astro-ls", "--stdio"]

[language-server.astro-ls-local.config.typescript]
tsdk = "./node_modules/typescript/lib"

[language-server.typescript-language-server-local]
command = "bun"
args = ["--bun", "./node_modules/.bin/typescript-language-server", "--stdio"]

[language-server.typescript-language-server-local.config]
hostInfo = "helix"

[language-server.typescript-language-server-local.config.tsserver]
path = "./node_modules/typescript/lib/tsserver.js"

[[language]]
name = "astro"
roots = ["astro.config.ts", "astro.config.mjs", "package.json"]
language-servers = ["astro-ls-local"]
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/prettier --plugin prettier-plugin-astro --stdin-filepath \"$1\"", "sh", "%{buffer_name}"] }

[[language]]
name = "typescript"
roots = ["tsconfig.json", "package.json"]
language-servers = ["typescript-language-server-local"]
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }

[[language]]
name = "tsx"
roots = ["tsconfig.json", "package.json"]
language-servers = ["typescript-language-server-local"]
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }

[[language]]
name = "javascript"
roots = ["package.json"]
language-servers = ["typescript-language-server-local"]
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }

[[language]]
name = "jsx"
roots = ["package.json"]
language-servers = ["typescript-language-server-local"]
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }

[[language]]
name = "html"
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/prettier --stdin-filepath \"$1\"", "sh", "%{buffer_name}"] }

[[language]]
name = "css"
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/prettier --stdin-filepath \"$1\"", "sh", "%{buffer_name}"] }

[[language]]
name = "json"
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }

[[language]]
name = "jsonc"
formatter = { command = "sh", args = ["-lc", "root=$(git rev-parse --show-toplevel) && exec direnv exec \"$root\" \"$root\"/node_modules/.bin/biome format --stdin-file-path \"$1\" --write", "sh", "%{buffer_name}"] }
